### ISSUE TITLE
v2.2.0

### ISSUE THREAD

**Issue by davedoesdev** [apowers313/fido2-lib#16]
I see `package.json` is at 2.2.0 but npm is at 2.1.1.
Just wondered if you forgot to publish.
No worries if it's work in progress, feel free to close immediately.

**Comment by davedoesdev** [comment]
Btw, great module- not failed yet.

**Comment by apowers313** [comment]
Thanks :)

The new features in 2.2.0 are extensions and MDS support. The problem I've encountered with deploying them are:

1. The AppID extension (which is the only one the browsers will support in the short term) only supports the U2F use case; that would require me building a U2F server and registering authenticators as U2F just to test it out.

2. Currently there are no authenticators with AAGUID registered in MDS, so I can't test out MDS right now.

**Comment by davedoesdev** [comment]
No problem. I was hoping to pick up https://github.com/apowers313/fido2-lib/commit/f8f1e39f7a4ab3eb0299f0b1ae54ef3817ccd9a3 but can live without it.
