### ISSUE TITLE
Soft token for testing

### ISSUE THREAD

**Issue by davedoesdev** [apowers313/fido2-lib#17]
Do you know if there's a soft token library available that would be suitable to use for testing?

At the moment I use webdriverio and Firefox, which is fine but requires me to have a hard token plugged in and press the button multiple times on each test.

For one of my projects I saved the responses and then replayed them (ignoring replay errors).

However it would by nice to have a library/program which would act like a hard token.

@apowers313 what do you use for testing?

**Comment by davedoesdev** [comment]
`security.webauth.webauthn_enable_softtoken` might do the trick

**Comment by apowers313** [comment]
I use helpers rather than live data:

https://github.com/apowers313/fido2-helpers

For final testing after deployment, I have a collection of U2F and CTAP tokens, as well as the Windows 10 Insider release that has a built-in authenticator.

Hope that helps.

**Comment by davedoesdev** [comment]
Mozilla soft token works a treat
